language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t tomerb/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tomerb/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-2'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-eu-west-2-846002051305'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: '$AWS_SECRET_KEY'
